import type { Config } from "./config";

export const CONFIGS = {
	js: {
		id: "js",
		label: ".js",
		family: "focus",
		description: "JS polls pay 1.5× — but if JS shows, you must get one right.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		focusCategory: "js",
	},
	ts: {
		id: "ts",
		label: ".ts",
		family: "focus",
		description: "TS polls pay 1.5× — but if TS shows, you must get one right.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		focusCategory: "ts",
	},
	css: {
		id: "css",
		label: ".css",
		family: "focus",
		description:
			"CSS polls pay 1.5× — but if CSS shows, you must get one right.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		focusCategory: "css",
	},
	jsx: {
		id: "jsx",
		label: ".jsx",
		family: "focus",
		description:
			"React polls pay 1.5× — but if React shows, you must get one right.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		focusCategory: "react",
	},
	git: {
		id: "git",
		label: ".git",
		family: "focus",
		description:
			"Git polls pay 1.5× — but if Git shows, you must get one right.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		focusCategory: "git",
	},
	rb: {
		id: "rb",
		label: ".rb",
		family: "focus",
		description:
			"Ruby polls pay 1.5× — but if Ruby shows, you must get one right.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		focusCategory: "ruby",
	},
	html: {
		id: "html",
		label: ".html",
		family: "focus",
		description:
			"HTML polls pay 1.5× — but if HTML shows, you must get one right.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		focusCategory: "html",
	},
	java: {
		id: "java",
		label: ".java",
		family: "focus",
		description:
			"Java polls pay 1.5× — but if Java shows, you must get one right.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		focusCategory: "java",
	},
	// Defense — linters disable a wrong option; yarn.lock locks the gate.
	eslint: {
		id: "eslint",
		label: "ESLint",
		family: "defense",
		description: "Disables one wrong answer on JS/TS polls.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		eliminatesWrongOptionsFor: ["js", "ts"],
	},
	stylelint: {
		id: "stylelint",
		label: "Stylelint",
		family: "defense",
		description: "Disables one wrong answer on CSS polls.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		eliminatesWrongOptionsFor: ["css"],
	},
	intellisense: {
		id: "intellisense",
		label: "Intellisense",
		family: "defense",
		rarity: "uncommon",
		description: "Disables one wrong answer on React/TS polls.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		eliminatesWrongOptionsFor: ["react", "ts"],
	},
	yarnLock: {
		id: "yarn-lock",
		label: "yarn.lock",
		family: "defense",
		rarity: "rare",
		description: "This gate can never get harder.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		immuneToRaise: true,
	},
	copilot: {
		id: "copilot",
		label: "Copilot",
		family: "amplify",
		rarity: "rare",
		description: "All coverage ×2.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		coverageMultiplier: 2,
	},
	codeCoverage: {
		id: "code-coverage",
		label: "Code Coverage",
		family: "amplify",
		rarity: "uncommon",
		description: "+0.5% flat coverage per correct answer.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		coverageAdd: 0.5,
	},
	indexedDb: {
		id: "indexed-db",
		label: "IndexedDB",
		family: "economy",
		rarity: "uncommon",
		description: "+8KB storage per correct answer.",
		requirementDelta: 0,
		rewardMultiplier: 1,
		storagePerCorrect: 8,
	},
	coverageGain: {
		id: "coverage-gain",
		label: "Coverage",
		family: "check",
		rarity: "uncommon",
		description: "Gate also needs +4% coverage — pays 1.5× storage.",
		requirementDelta: 0,
		rewardMultiplier: 1.5,
		check: "coverage-gain",
		checkAmount: 4,
	},
	coldStart: {
		id: "cold-start",
		label: "Cold Start",
		family: "check",
		rarity: "uncommon",
		description:
			"Gate also needs your first 2 answers correct — pays 1.5× storage.",
		requirementDelta: 0,
		rewardMultiplier: 1.5,
		check: "cold-start",
		checkAmount: 2,
	},
	speed: {
		id: "speed",
		label: "Speed",
		family: "check",
		rarity: "uncommon",
		description: "Gate also needs 2 fast answers — pays 2× storage.",
		requirementDelta: 0,
		rewardMultiplier: 2,
		check: "speed",
		checkAmount: 2,
	},
	pushForce: {
		id: "push-force",
		label: "push --force",
		family: "risk",
		rarity: "uncommon",
		description: "Gate needs 1 more correct — but pays 2× storage.",
		requirementDelta: 1,
		rewardMultiplier: 2,
	},
	deployFriday: {
		id: "deploy-friday",
		label: "Deploy on Friday",
		family: "risk",
		rarity: "legendary",
		description: "Gate needs 2 more correct — but pays 3× storage.",
		requirementDelta: 2,
		rewardMultiplier: 3,
	},
} as const satisfies Record<string, Config>;

export const CONFIG_LIST: readonly Config[] = Object.values(CONFIGS);
