/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ProtoSessionSliceRouteImport } from './routes/proto-session-slice'
import { Route as ProtoRunRouteImport } from './routes/proto-run'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OldStartRouteImport } from './routes/old/start'
import { Route as OldShopRouteImport } from './routes/old/shop'
import { Route as OldPipelinesRouteImport } from './routes/old/pipelines'
import { Route as OldPipelineSuccessRouteImport } from './routes/old/pipeline-success'
import { Route as OldPipelineFailureRouteImport } from './routes/old/pipeline-failure'
import { Route as OldGameOverRouteImport } from './routes/old/game-over'
import { Route as OldCommunityRouteImport } from './routes/old/community'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedDexRouteImport } from './routes/_authed/dex'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedRunRouteRouteImport } from './routes/_authed/run/route'
import { Route as OldDailyPollIndexRouteImport } from './routes/old/daily-poll/index'
import { Route as AuthedRunIndexRouteImport } from './routes/_authed/run/index'
import { Route as AuthedPollsIndexRouteImport } from './routes/_authed/polls/index'
import { Route as OldRunCommunityRouteImport } from './routes/old/run_.community'
import { Route as AuthedRunCommunityRouteImport } from './routes/_authed/run_.community'
import { Route as AuthedRunStripRouteImport } from './routes/_authed/run/strip'
import { Route as AuthedRunShopRouteImport } from './routes/_authed/run/shop'
import { Route as AuthedRunRewardRouteImport } from './routes/_authed/run/reward'
import { Route as AuthedRunReviewRouteImport } from './routes/_authed/run/review'
import { Route as AuthedRunOverRouteImport } from './routes/_authed/run/over'
import { Route as AuthedRunConfigureRouteImport } from './routes/_authed/run/configure'
import { Route as AuthedRunAnswerRouteImport } from './routes/_authed/run/answer'
import { Route as AuthedProfileUserIdRouteImport } from './routes/_authed/profile.$userId'
import { Route as AuthedPollsNewRouteImport } from './routes/_authed/polls/new'
import { Route as AuthedPollsPollIdIndexRouteImport } from './routes/_authed/polls/$pollId/index'
import { Route as AuthedPollsPollIdEditRouteImport } from './routes/_authed/polls/$pollId/edit'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoSessionSliceRoute = ProtoSessionSliceRouteImport.update({
  id: '/proto-session-slice',
  path: '/proto-session-slice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoRunRoute = ProtoRunRouteImport.update({
  id: '/proto-run',
  path: '/proto-run',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OldStartRoute = OldStartRouteImport.update({
  id: '/old/start',
  path: '/old/start',
  getParentRoute: () => rootRouteImport,
} as any)
const OldShopRoute = OldShopRouteImport.update({
  id: '/old/shop',
  path: '/old/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OldPipelinesRoute = OldPipelinesRouteImport.update({
  id: '/old/pipelines',
  path: '/old/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const OldPipelineSuccessRoute = OldPipelineSuccessRouteImport.update({
  id: '/old/pipeline-success',
  path: '/old/pipeline-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OldPipelineFailureRoute = OldPipelineFailureRouteImport.update({
  id: '/old/pipeline-failure',
  path: '/old/pipeline-failure',
  getParentRoute: () => rootRouteImport,
} as any)
const OldGameOverRoute = OldGameOverRouteImport.update({
  id: '/old/game-over',
  path: '/old/game-over',
  getParentRoute: () => rootRouteImport,
} as any)
const OldCommunityRoute = OldCommunityRouteImport.update({
  id: '/old/community',
  path: '/old/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDexRoute = AuthedDexRouteImport.update({
  id: '/dex',
  path: '/dex',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRunRouteRoute = AuthedRunRouteRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => AuthedRoute,
} as any)
const OldDailyPollIndexRoute = OldDailyPollIndexRouteImport.update({
  id: '/old/daily-poll/',
  path: '/old/daily-poll/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRunIndexRoute = AuthedRunIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRunRouteRoute,
} as any)
const AuthedPollsIndexRoute = AuthedPollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => AuthedRoute,
} as any)
const OldRunCommunityRoute = OldRunCommunityRouteImport.update({
  id: '/old/run_/community',
  path: '/old/run/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRunCommunityRoute = AuthedRunCommunityRouteImport.update({
  id: '/run_/community',
  path: '/run/community',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRunStripRoute = AuthedRunStripRouteImport.update({
  id: '/strip',
  path: '/strip',
  getParentRoute: () => AuthedRunRouteRoute,
} as any)
const AuthedRunShopRoute = AuthedRunShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthedRunRouteRoute,
} as any)
const AuthedRunRewardRoute = AuthedRunRewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => AuthedRunRouteRoute,
} as any)
const AuthedRunReviewRoute = AuthedRunReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthedRunRouteRoute,
} as any)
const AuthedRunOverRoute = AuthedRunOverRouteImport.update({
  id: '/over',
  path: '/over',
  getParentRoute: () => AuthedRunRouteRoute,
} as any)
const AuthedRunConfigureRoute = AuthedRunConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => AuthedRunRouteRoute,
} as any)
const AuthedRunAnswerRoute = AuthedRunAnswerRouteImport.update({
  id: '/answer',
  path: '/answer',
  getParentRoute: () => AuthedRunRouteRoute,
} as any)
const AuthedProfileUserIdRoute = AuthedProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPollsNewRoute = AuthedPollsNewRouteImport.update({
  id: '/polls/new',
  path: '/polls/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPollsPollIdIndexRoute = AuthedPollsPollIdIndexRouteImport.update({
  id: '/polls/$pollId/',
  path: '/polls/$pollId/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPollsPollIdEditRoute = AuthedPollsPollIdEditRouteImport.update({
  id: '/polls/$pollId/edit',
  path: '/polls/$pollId/edit',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/presentation': typeof PresentationRoute
  '/proto-run': typeof ProtoRunRoute
  '/proto-session-slice': typeof ProtoSessionSliceRoute
  '/sign-up': typeof SignUpRoute
  '/stats': typeof StatsRoute
  '/run': typeof AuthedRunRouteRouteWithChildren
  '/admin': typeof AuthedAdminRoute
  '/dex': typeof AuthedDexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/old/community': typeof OldCommunityRoute
  '/old/game-over': typeof OldGameOverRoute
  '/old/pipeline-failure': typeof OldPipelineFailureRoute
  '/old/pipeline-success': typeof OldPipelineSuccessRoute
  '/old/pipelines': typeof OldPipelinesRoute
  '/old/shop': typeof OldShopRoute
  '/old/start': typeof OldStartRoute
  '/polls/new': typeof AuthedPollsNewRoute
  '/profile/$userId': typeof AuthedProfileUserIdRoute
  '/run/answer': typeof AuthedRunAnswerRoute
  '/run/configure': typeof AuthedRunConfigureRoute
  '/run/over': typeof AuthedRunOverRoute
  '/run/review': typeof AuthedRunReviewRoute
  '/run/reward': typeof AuthedRunRewardRoute
  '/run/shop': typeof AuthedRunShopRoute
  '/run/strip': typeof AuthedRunStripRoute
  '/run/community': typeof AuthedRunCommunityRoute
  '/old/run/community': typeof OldRunCommunityRoute
  '/polls/': typeof AuthedPollsIndexRoute
  '/run/': typeof AuthedRunIndexRoute
  '/old/daily-poll/': typeof OldDailyPollIndexRoute
  '/polls/$pollId/edit': typeof AuthedPollsPollIdEditRoute
  '/polls/$pollId/': typeof AuthedPollsPollIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/presentation': typeof PresentationRoute
  '/proto-run': typeof ProtoRunRoute
  '/proto-session-slice': typeof ProtoSessionSliceRoute
  '/sign-up': typeof SignUpRoute
  '/stats': typeof StatsRoute
  '/admin': typeof AuthedAdminRoute
  '/dex': typeof AuthedDexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/old/community': typeof OldCommunityRoute
  '/old/game-over': typeof OldGameOverRoute
  '/old/pipeline-failure': typeof OldPipelineFailureRoute
  '/old/pipeline-success': typeof OldPipelineSuccessRoute
  '/old/pipelines': typeof OldPipelinesRoute
  '/old/shop': typeof OldShopRoute
  '/old/start': typeof OldStartRoute
  '/polls/new': typeof AuthedPollsNewRoute
  '/profile/$userId': typeof AuthedProfileUserIdRoute
  '/run/answer': typeof AuthedRunAnswerRoute
  '/run/configure': typeof AuthedRunConfigureRoute
  '/run/over': typeof AuthedRunOverRoute
  '/run/review': typeof AuthedRunReviewRoute
  '/run/reward': typeof AuthedRunRewardRoute
  '/run/shop': typeof AuthedRunShopRoute
  '/run/strip': typeof AuthedRunStripRoute
  '/run/community': typeof AuthedRunCommunityRoute
  '/old/run/community': typeof OldRunCommunityRoute
  '/polls': typeof AuthedPollsIndexRoute
  '/run': typeof AuthedRunIndexRoute
  '/old/daily-poll': typeof OldDailyPollIndexRoute
  '/polls/$pollId/edit': typeof AuthedPollsPollIdEditRoute
  '/polls/$pollId': typeof AuthedPollsPollIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/presentation': typeof PresentationRoute
  '/proto-run': typeof ProtoRunRoute
  '/proto-session-slice': typeof ProtoSessionSliceRoute
  '/sign-up': typeof SignUpRoute
  '/stats': typeof StatsRoute
  '/_authed/run': typeof AuthedRunRouteRouteWithChildren
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/dex': typeof AuthedDexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/old/community': typeof OldCommunityRoute
  '/old/game-over': typeof OldGameOverRoute
  '/old/pipeline-failure': typeof OldPipelineFailureRoute
  '/old/pipeline-success': typeof OldPipelineSuccessRoute
  '/old/pipelines': typeof OldPipelinesRoute
  '/old/shop': typeof OldShopRoute
  '/old/start': typeof OldStartRoute
  '/_authed/polls/new': typeof AuthedPollsNewRoute
  '/_authed/profile/$userId': typeof AuthedProfileUserIdRoute
  '/_authed/run/answer': typeof AuthedRunAnswerRoute
  '/_authed/run/configure': typeof AuthedRunConfigureRoute
  '/_authed/run/over': typeof AuthedRunOverRoute
  '/_authed/run/review': typeof AuthedRunReviewRoute
  '/_authed/run/reward': typeof AuthedRunRewardRoute
  '/_authed/run/shop': typeof AuthedRunShopRoute
  '/_authed/run/strip': typeof AuthedRunStripRoute
  '/_authed/run_/community': typeof AuthedRunCommunityRoute
  '/old/run_/community': typeof OldRunCommunityRoute
  '/_authed/polls/': typeof AuthedPollsIndexRoute
  '/_authed/run/': typeof AuthedRunIndexRoute
  '/old/daily-poll/': typeof OldDailyPollIndexRoute
  '/_authed/polls/$pollId/edit': typeof AuthedPollsPollIdEditRoute
  '/_authed/polls/$pollId/': typeof AuthedPollsPollIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/presentation'
    | '/proto-run'
    | '/proto-session-slice'
    | '/sign-up'
    | '/stats'
    | '/run'
    | '/admin'
    | '/dex'
    | '/auth/callback'
    | '/old/community'
    | '/old/game-over'
    | '/old/pipeline-failure'
    | '/old/pipeline-success'
    | '/old/pipelines'
    | '/old/shop'
    | '/old/start'
    | '/polls/new'
    | '/profile/$userId'
    | '/run/answer'
    | '/run/configure'
    | '/run/over'
    | '/run/review'
    | '/run/reward'
    | '/run/shop'
    | '/run/strip'
    | '/run/community'
    | '/old/run/community'
    | '/polls/'
    | '/run/'
    | '/old/daily-poll/'
    | '/polls/$pollId/edit'
    | '/polls/$pollId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/presentation'
    | '/proto-run'
    | '/proto-session-slice'
    | '/sign-up'
    | '/stats'
    | '/admin'
    | '/dex'
    | '/auth/callback'
    | '/old/community'
    | '/old/game-over'
    | '/old/pipeline-failure'
    | '/old/pipeline-success'
    | '/old/pipelines'
    | '/old/shop'
    | '/old/start'
    | '/polls/new'
    | '/profile/$userId'
    | '/run/answer'
    | '/run/configure'
    | '/run/over'
    | '/run/review'
    | '/run/reward'
    | '/run/shop'
    | '/run/strip'
    | '/run/community'
    | '/old/run/community'
    | '/polls'
    | '/run'
    | '/old/daily-poll'
    | '/polls/$pollId/edit'
    | '/polls/$pollId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/presentation'
    | '/proto-run'
    | '/proto-session-slice'
    | '/sign-up'
    | '/stats'
    | '/_authed/run'
    | '/_authed/admin'
    | '/_authed/dex'
    | '/auth/callback'
    | '/old/community'
    | '/old/game-over'
    | '/old/pipeline-failure'
    | '/old/pipeline-success'
    | '/old/pipelines'
    | '/old/shop'
    | '/old/start'
    | '/_authed/polls/new'
    | '/_authed/profile/$userId'
    | '/_authed/run/answer'
    | '/_authed/run/configure'
    | '/_authed/run/over'
    | '/_authed/run/review'
    | '/_authed/run/reward'
    | '/_authed/run/shop'
    | '/_authed/run/strip'
    | '/_authed/run_/community'
    | '/old/run_/community'
    | '/_authed/polls/'
    | '/_authed/run/'
    | '/old/daily-poll/'
    | '/_authed/polls/$pollId/edit'
    | '/_authed/polls/$pollId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PresentationRoute: typeof PresentationRoute
  ProtoRunRoute: typeof ProtoRunRoute
  ProtoSessionSliceRoute: typeof ProtoSessionSliceRoute
  SignUpRoute: typeof SignUpRoute
  StatsRoute: typeof StatsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  OldCommunityRoute: typeof OldCommunityRoute
  OldGameOverRoute: typeof OldGameOverRoute
  OldPipelineFailureRoute: typeof OldPipelineFailureRoute
  OldPipelineSuccessRoute: typeof OldPipelineSuccessRoute
  OldPipelinesRoute: typeof OldPipelinesRoute
  OldShopRoute: typeof OldShopRoute
  OldStartRoute: typeof OldStartRoute
  OldRunCommunityRoute: typeof OldRunCommunityRoute
  OldDailyPollIndexRoute: typeof OldDailyPollIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto-session-slice': {
      id: '/proto-session-slice'
      path: '/proto-session-slice'
      fullPath: '/proto-session-slice'
      preLoaderRoute: typeof ProtoSessionSliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto-run': {
      id: '/proto-run'
      path: '/proto-run'
      fullPath: '/proto-run'
      preLoaderRoute: typeof ProtoRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old/start': {
      id: '/old/start'
      path: '/old/start'
      fullPath: '/old/start'
      preLoaderRoute: typeof OldStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old/shop': {
      id: '/old/shop'
      path: '/old/shop'
      fullPath: '/old/shop'
      preLoaderRoute: typeof OldShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old/pipelines': {
      id: '/old/pipelines'
      path: '/old/pipelines'
      fullPath: '/old/pipelines'
      preLoaderRoute: typeof OldPipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old/pipeline-success': {
      id: '/old/pipeline-success'
      path: '/old/pipeline-success'
      fullPath: '/old/pipeline-success'
      preLoaderRoute: typeof OldPipelineSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old/pipeline-failure': {
      id: '/old/pipeline-failure'
      path: '/old/pipeline-failure'
      fullPath: '/old/pipeline-failure'
      preLoaderRoute: typeof OldPipelineFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old/game-over': {
      id: '/old/game-over'
      path: '/old/game-over'
      fullPath: '/old/game-over'
      preLoaderRoute: typeof OldGameOverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old/community': {
      id: '/old/community'
      path: '/old/community'
      fullPath: '/old/community'
      preLoaderRoute: typeof OldCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dex': {
      id: '/_authed/dex'
      path: '/dex'
      fullPath: '/dex'
      preLoaderRoute: typeof AuthedDexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/run': {
      id: '/_authed/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof AuthedRunRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/old/daily-poll/': {
      id: '/old/daily-poll/'
      path: '/old/daily-poll'
      fullPath: '/old/daily-poll/'
      preLoaderRoute: typeof OldDailyPollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/run/': {
      id: '/_authed/run/'
      path: '/'
      fullPath: '/run/'
      preLoaderRoute: typeof AuthedRunIndexRouteImport
      parentRoute: typeof AuthedRunRouteRoute
    }
    '/_authed/polls/': {
      id: '/_authed/polls/'
      path: '/polls'
      fullPath: '/polls/'
      preLoaderRoute: typeof AuthedPollsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/old/run_/community': {
      id: '/old/run_/community'
      path: '/old/run/community'
      fullPath: '/old/run/community'
      preLoaderRoute: typeof OldRunCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/run_/community': {
      id: '/_authed/run_/community'
      path: '/run/community'
      fullPath: '/run/community'
      preLoaderRoute: typeof AuthedRunCommunityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/run/strip': {
      id: '/_authed/run/strip'
      path: '/strip'
      fullPath: '/run/strip'
      preLoaderRoute: typeof AuthedRunStripRouteImport
      parentRoute: typeof AuthedRunRouteRoute
    }
    '/_authed/run/shop': {
      id: '/_authed/run/shop'
      path: '/shop'
      fullPath: '/run/shop'
      preLoaderRoute: typeof AuthedRunShopRouteImport
      parentRoute: typeof AuthedRunRouteRoute
    }
    '/_authed/run/reward': {
      id: '/_authed/run/reward'
      path: '/reward'
      fullPath: '/run/reward'
      preLoaderRoute: typeof AuthedRunRewardRouteImport
      parentRoute: typeof AuthedRunRouteRoute
    }
    '/_authed/run/review': {
      id: '/_authed/run/review'
      path: '/review'
      fullPath: '/run/review'
      preLoaderRoute: typeof AuthedRunReviewRouteImport
      parentRoute: typeof AuthedRunRouteRoute
    }
    '/_authed/run/over': {
      id: '/_authed/run/over'
      path: '/over'
      fullPath: '/run/over'
      preLoaderRoute: typeof AuthedRunOverRouteImport
      parentRoute: typeof AuthedRunRouteRoute
    }
    '/_authed/run/configure': {
      id: '/_authed/run/configure'
      path: '/configure'
      fullPath: '/run/configure'
      preLoaderRoute: typeof AuthedRunConfigureRouteImport
      parentRoute: typeof AuthedRunRouteRoute
    }
    '/_authed/run/answer': {
      id: '/_authed/run/answer'
      path: '/answer'
      fullPath: '/run/answer'
      preLoaderRoute: typeof AuthedRunAnswerRouteImport
      parentRoute: typeof AuthedRunRouteRoute
    }
    '/_authed/profile/$userId': {
      id: '/_authed/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthedProfileUserIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/polls/new': {
      id: '/_authed/polls/new'
      path: '/polls/new'
      fullPath: '/polls/new'
      preLoaderRoute: typeof AuthedPollsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/polls/$pollId/': {
      id: '/_authed/polls/$pollId/'
      path: '/polls/$pollId'
      fullPath: '/polls/$pollId/'
      preLoaderRoute: typeof AuthedPollsPollIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/polls/$pollId/edit': {
      id: '/_authed/polls/$pollId/edit'
      path: '/polls/$pollId/edit'
      fullPath: '/polls/$pollId/edit'
      preLoaderRoute: typeof AuthedPollsPollIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRunRouteRouteChildren {
  AuthedRunAnswerRoute: typeof AuthedRunAnswerRoute
  AuthedRunConfigureRoute: typeof AuthedRunConfigureRoute
  AuthedRunOverRoute: typeof AuthedRunOverRoute
  AuthedRunReviewRoute: typeof AuthedRunReviewRoute
  AuthedRunRewardRoute: typeof AuthedRunRewardRoute
  AuthedRunShopRoute: typeof AuthedRunShopRoute
  AuthedRunStripRoute: typeof AuthedRunStripRoute
  AuthedRunIndexRoute: typeof AuthedRunIndexRoute
}

const AuthedRunRouteRouteChildren: AuthedRunRouteRouteChildren = {
  AuthedRunAnswerRoute: AuthedRunAnswerRoute,
  AuthedRunConfigureRoute: AuthedRunConfigureRoute,
  AuthedRunOverRoute: AuthedRunOverRoute,
  AuthedRunReviewRoute: AuthedRunReviewRoute,
  AuthedRunRewardRoute: AuthedRunRewardRoute,
  AuthedRunShopRoute: AuthedRunShopRoute,
  AuthedRunStripRoute: AuthedRunStripRoute,
  AuthedRunIndexRoute: AuthedRunIndexRoute,
}

const AuthedRunRouteRouteWithChildren = AuthedRunRouteRoute._addFileChildren(
  AuthedRunRouteRouteChildren,
)

interface AuthedRouteChildren {
  AuthedRunRouteRoute: typeof AuthedRunRouteRouteWithChildren
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedDexRoute: typeof AuthedDexRoute
  AuthedPollsNewRoute: typeof AuthedPollsNewRoute
  AuthedProfileUserIdRoute: typeof AuthedProfileUserIdRoute
  AuthedRunCommunityRoute: typeof AuthedRunCommunityRoute
  AuthedPollsIndexRoute: typeof AuthedPollsIndexRoute
  AuthedPollsPollIdEditRoute: typeof AuthedPollsPollIdEditRoute
  AuthedPollsPollIdIndexRoute: typeof AuthedPollsPollIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedRunRouteRoute: AuthedRunRouteRouteWithChildren,
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedDexRoute: AuthedDexRoute,
  AuthedPollsNewRoute: AuthedPollsNewRoute,
  AuthedProfileUserIdRoute: AuthedProfileUserIdRoute,
  AuthedRunCommunityRoute: AuthedRunCommunityRoute,
  AuthedPollsIndexRoute: AuthedPollsIndexRoute,
  AuthedPollsPollIdEditRoute: AuthedPollsPollIdEditRoute,
  AuthedPollsPollIdIndexRoute: AuthedPollsPollIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PresentationRoute: PresentationRoute,
  ProtoRunRoute: ProtoRunRoute,
  ProtoSessionSliceRoute: ProtoSessionSliceRoute,
  SignUpRoute: SignUpRoute,
  StatsRoute: StatsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  OldCommunityRoute: OldCommunityRoute,
  OldGameOverRoute: OldGameOverRoute,
  OldPipelineFailureRoute: OldPipelineFailureRoute,
  OldPipelineSuccessRoute: OldPipelineSuccessRoute,
  OldPipelinesRoute: OldPipelinesRoute,
  OldShopRoute: OldShopRoute,
  OldStartRoute: OldStartRoute,
  OldRunCommunityRoute: OldRunCommunityRoute,
  OldDailyPollIndexRoute: OldDailyPollIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
