/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedGameOverRouteImport } from './routes/_authed/game-over'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedPollsIndexRouteImport } from './routes/_authed/polls/index'
import { Route as AuthedDailyPollIndexRouteImport } from './routes/_authed/daily-poll/index'
import { Route as AuthedProfileUserIdRouteImport } from './routes/_authed/profile.$userId'
import { Route as AuthedPollsPollIdRouteImport } from './routes/_authed/polls/$pollId'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedGameOverRoute = AuthedGameOverRouteImport.update({
  id: '/game-over',
  path: '/game-over',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPollsIndexRoute = AuthedPollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDailyPollIndexRoute = AuthedDailyPollIndexRouteImport.update({
  id: '/daily-poll/',
  path: '/daily-poll/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileUserIdRoute = AuthedProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPollsPollIdRoute = AuthedPollsPollIdRouteImport.update({
  id: '/polls/$pollId',
  path: '/polls/$pollId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/sign-up': typeof SignUpRoute
  '/start': typeof StartRoute
  '/admin': typeof AuthedAdminRoute
  '/game-over': typeof AuthedGameOverRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/polls/$pollId': typeof AuthedPollsPollIdRoute
  '/profile/$userId': typeof AuthedProfileUserIdRoute
  '/daily-poll': typeof AuthedDailyPollIndexRoute
  '/polls': typeof AuthedPollsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/sign-up': typeof SignUpRoute
  '/start': typeof StartRoute
  '/admin': typeof AuthedAdminRoute
  '/game-over': typeof AuthedGameOverRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/polls/$pollId': typeof AuthedPollsPollIdRoute
  '/profile/$userId': typeof AuthedProfileUserIdRoute
  '/daily-poll': typeof AuthedDailyPollIndexRoute
  '/polls': typeof AuthedPollsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/sign-up': typeof SignUpRoute
  '/start': typeof StartRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/game-over': typeof AuthedGameOverRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/polls/$pollId': typeof AuthedPollsPollIdRoute
  '/_authed/profile/$userId': typeof AuthedProfileUserIdRoute
  '/_authed/daily-poll/': typeof AuthedDailyPollIndexRoute
  '/_authed/polls/': typeof AuthedPollsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/sign-up'
    | '/start'
    | '/admin'
    | '/game-over'
    | '/auth/callback'
    | '/polls/$pollId'
    | '/profile/$userId'
    | '/daily-poll'
    | '/polls'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/sign-up'
    | '/start'
    | '/admin'
    | '/game-over'
    | '/auth/callback'
    | '/polls/$pollId'
    | '/profile/$userId'
    | '/daily-poll'
    | '/polls'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/sign-up'
    | '/start'
    | '/_authed/admin'
    | '/_authed/game-over'
    | '/auth/callback'
    | '/_authed/polls/$pollId'
    | '/_authed/profile/$userId'
    | '/_authed/daily-poll/'
    | '/_authed/polls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignUpRoute: typeof SignUpRoute
  StartRoute: typeof StartRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/game-over': {
      id: '/_authed/game-over'
      path: '/game-over'
      fullPath: '/game-over'
      preLoaderRoute: typeof AuthedGameOverRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/polls/': {
      id: '/_authed/polls/'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof AuthedPollsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/daily-poll/': {
      id: '/_authed/daily-poll/'
      path: '/daily-poll'
      fullPath: '/daily-poll'
      preLoaderRoute: typeof AuthedDailyPollIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile/$userId': {
      id: '/_authed/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthedProfileUserIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/polls/$pollId': {
      id: '/_authed/polls/$pollId'
      path: '/polls/$pollId'
      fullPath: '/polls/$pollId'
      preLoaderRoute: typeof AuthedPollsPollIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedGameOverRoute: typeof AuthedGameOverRoute
  AuthedPollsPollIdRoute: typeof AuthedPollsPollIdRoute
  AuthedProfileUserIdRoute: typeof AuthedProfileUserIdRoute
  AuthedDailyPollIndexRoute: typeof AuthedDailyPollIndexRoute
  AuthedPollsIndexRoute: typeof AuthedPollsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedGameOverRoute: AuthedGameOverRoute,
  AuthedPollsPollIdRoute: AuthedPollsPollIdRoute,
  AuthedProfileUserIdRoute: AuthedProfileUserIdRoute,
  AuthedDailyPollIndexRoute: AuthedDailyPollIndexRoute,
  AuthedPollsIndexRoute: AuthedPollsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignUpRoute: SignUpRoute,
  StartRoute: StartRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
