/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StartRouteImport } from './routes/start'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedShopRouteImport } from './routes/_authed/shop'
import { Route as AuthedPipelinesRouteImport } from './routes/_authed/pipelines'
import { Route as AuthedPipelineSuccessRouteImport } from './routes/_authed/pipeline-success'
import { Route as AuthedPipelineFailureRouteImport } from './routes/_authed/pipeline-failure'
import { Route as AuthedGameOverRouteImport } from './routes/_authed/game-over'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedPollsIndexRouteImport } from './routes/_authed/polls/index'
import { Route as AuthedDailyPollIndexRouteImport } from './routes/_authed/daily-poll/index'
import { Route as AuthedProfileUserIdRouteImport } from './routes/_authed/profile.$userId'
import { Route as AuthedPollsNewRouteImport } from './routes/_authed/polls/new'
import { Route as AuthedPollsPollIdIndexRouteImport } from './routes/_authed/polls/$pollId/index'
import { Route as AuthedPollsPollIdEditRouteImport } from './routes/_authed/polls/$pollId/edit'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedShopRoute = AuthedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPipelinesRoute = AuthedPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPipelineSuccessRoute = AuthedPipelineSuccessRouteImport.update({
  id: '/pipeline-success',
  path: '/pipeline-success',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPipelineFailureRoute = AuthedPipelineFailureRouteImport.update({
  id: '/pipeline-failure',
  path: '/pipeline-failure',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGameOverRoute = AuthedGameOverRouteImport.update({
  id: '/game-over',
  path: '/game-over',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPollsIndexRoute = AuthedPollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDailyPollIndexRoute = AuthedDailyPollIndexRouteImport.update({
  id: '/daily-poll/',
  path: '/daily-poll/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileUserIdRoute = AuthedProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPollsNewRoute = AuthedPollsNewRouteImport.update({
  id: '/polls/new',
  path: '/polls/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPollsPollIdIndexRoute = AuthedPollsPollIdIndexRouteImport.update({
  id: '/polls/$pollId/',
  path: '/polls/$pollId/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPollsPollIdEditRoute = AuthedPollsPollIdEditRouteImport.update({
  id: '/polls/$pollId/edit',
  path: '/polls/$pollId/edit',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/presentation': typeof PresentationRoute
  '/sign-up': typeof SignUpRoute
  '/start': typeof StartRoute
  '/stats': typeof StatsRoute
  '/admin': typeof AuthedAdminRoute
  '/game-over': typeof AuthedGameOverRoute
  '/pipeline-failure': typeof AuthedPipelineFailureRoute
  '/pipeline-success': typeof AuthedPipelineSuccessRoute
  '/pipelines': typeof AuthedPipelinesRoute
  '/shop': typeof AuthedShopRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/polls/new': typeof AuthedPollsNewRoute
  '/profile/$userId': typeof AuthedProfileUserIdRoute
  '/daily-poll/': typeof AuthedDailyPollIndexRoute
  '/polls/': typeof AuthedPollsIndexRoute
  '/polls/$pollId/edit': typeof AuthedPollsPollIdEditRoute
  '/polls/$pollId/': typeof AuthedPollsPollIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/presentation': typeof PresentationRoute
  '/sign-up': typeof SignUpRoute
  '/start': typeof StartRoute
  '/stats': typeof StatsRoute
  '/admin': typeof AuthedAdminRoute
  '/game-over': typeof AuthedGameOverRoute
  '/pipeline-failure': typeof AuthedPipelineFailureRoute
  '/pipeline-success': typeof AuthedPipelineSuccessRoute
  '/pipelines': typeof AuthedPipelinesRoute
  '/shop': typeof AuthedShopRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/polls/new': typeof AuthedPollsNewRoute
  '/profile/$userId': typeof AuthedProfileUserIdRoute
  '/daily-poll': typeof AuthedDailyPollIndexRoute
  '/polls': typeof AuthedPollsIndexRoute
  '/polls/$pollId/edit': typeof AuthedPollsPollIdEditRoute
  '/polls/$pollId': typeof AuthedPollsPollIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/awards': typeof AwardsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/presentation': typeof PresentationRoute
  '/sign-up': typeof SignUpRoute
  '/start': typeof StartRoute
  '/stats': typeof StatsRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/game-over': typeof AuthedGameOverRoute
  '/_authed/pipeline-failure': typeof AuthedPipelineFailureRoute
  '/_authed/pipeline-success': typeof AuthedPipelineSuccessRoute
  '/_authed/pipelines': typeof AuthedPipelinesRoute
  '/_authed/shop': typeof AuthedShopRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/polls/new': typeof AuthedPollsNewRoute
  '/_authed/profile/$userId': typeof AuthedProfileUserIdRoute
  '/_authed/daily-poll/': typeof AuthedDailyPollIndexRoute
  '/_authed/polls/': typeof AuthedPollsIndexRoute
  '/_authed/polls/$pollId/edit': typeof AuthedPollsPollIdEditRoute
  '/_authed/polls/$pollId/': typeof AuthedPollsPollIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awards'
    | '/login'
    | '/logout'
    | '/presentation'
    | '/sign-up'
    | '/start'
    | '/stats'
    | '/admin'
    | '/game-over'
    | '/pipeline-failure'
    | '/pipeline-success'
    | '/pipelines'
    | '/shop'
    | '/auth/callback'
    | '/polls/new'
    | '/profile/$userId'
    | '/daily-poll/'
    | '/polls/'
    | '/polls/$pollId/edit'
    | '/polls/$pollId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/login'
    | '/logout'
    | '/presentation'
    | '/sign-up'
    | '/start'
    | '/stats'
    | '/admin'
    | '/game-over'
    | '/pipeline-failure'
    | '/pipeline-success'
    | '/pipelines'
    | '/shop'
    | '/auth/callback'
    | '/polls/new'
    | '/profile/$userId'
    | '/daily-poll'
    | '/polls'
    | '/polls/$pollId/edit'
    | '/polls/$pollId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/awards'
    | '/login'
    | '/logout'
    | '/presentation'
    | '/sign-up'
    | '/start'
    | '/stats'
    | '/_authed/admin'
    | '/_authed/game-over'
    | '/_authed/pipeline-failure'
    | '/_authed/pipeline-success'
    | '/_authed/pipelines'
    | '/_authed/shop'
    | '/auth/callback'
    | '/_authed/polls/new'
    | '/_authed/profile/$userId'
    | '/_authed/daily-poll/'
    | '/_authed/polls/'
    | '/_authed/polls/$pollId/edit'
    | '/_authed/polls/$pollId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AwardsRoute: typeof AwardsRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PresentationRoute: typeof PresentationRoute
  SignUpRoute: typeof SignUpRoute
  StartRoute: typeof StartRoute
  StatsRoute: typeof StatsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/shop': {
      id: '/_authed/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthedShopRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pipelines': {
      id: '/_authed/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof AuthedPipelinesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pipeline-success': {
      id: '/_authed/pipeline-success'
      path: '/pipeline-success'
      fullPath: '/pipeline-success'
      preLoaderRoute: typeof AuthedPipelineSuccessRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pipeline-failure': {
      id: '/_authed/pipeline-failure'
      path: '/pipeline-failure'
      fullPath: '/pipeline-failure'
      preLoaderRoute: typeof AuthedPipelineFailureRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/game-over': {
      id: '/_authed/game-over'
      path: '/game-over'
      fullPath: '/game-over'
      preLoaderRoute: typeof AuthedGameOverRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/polls/': {
      id: '/_authed/polls/'
      path: '/polls'
      fullPath: '/polls/'
      preLoaderRoute: typeof AuthedPollsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/daily-poll/': {
      id: '/_authed/daily-poll/'
      path: '/daily-poll'
      fullPath: '/daily-poll/'
      preLoaderRoute: typeof AuthedDailyPollIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile/$userId': {
      id: '/_authed/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthedProfileUserIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/polls/new': {
      id: '/_authed/polls/new'
      path: '/polls/new'
      fullPath: '/polls/new'
      preLoaderRoute: typeof AuthedPollsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/polls/$pollId/': {
      id: '/_authed/polls/$pollId/'
      path: '/polls/$pollId'
      fullPath: '/polls/$pollId/'
      preLoaderRoute: typeof AuthedPollsPollIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/polls/$pollId/edit': {
      id: '/_authed/polls/$pollId/edit'
      path: '/polls/$pollId/edit'
      fullPath: '/polls/$pollId/edit'
      preLoaderRoute: typeof AuthedPollsPollIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedGameOverRoute: typeof AuthedGameOverRoute
  AuthedPipelineFailureRoute: typeof AuthedPipelineFailureRoute
  AuthedPipelineSuccessRoute: typeof AuthedPipelineSuccessRoute
  AuthedPipelinesRoute: typeof AuthedPipelinesRoute
  AuthedShopRoute: typeof AuthedShopRoute
  AuthedPollsNewRoute: typeof AuthedPollsNewRoute
  AuthedProfileUserIdRoute: typeof AuthedProfileUserIdRoute
  AuthedDailyPollIndexRoute: typeof AuthedDailyPollIndexRoute
  AuthedPollsIndexRoute: typeof AuthedPollsIndexRoute
  AuthedPollsPollIdEditRoute: typeof AuthedPollsPollIdEditRoute
  AuthedPollsPollIdIndexRoute: typeof AuthedPollsPollIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedGameOverRoute: AuthedGameOverRoute,
  AuthedPipelineFailureRoute: AuthedPipelineFailureRoute,
  AuthedPipelineSuccessRoute: AuthedPipelineSuccessRoute,
  AuthedPipelinesRoute: AuthedPipelinesRoute,
  AuthedShopRoute: AuthedShopRoute,
  AuthedPollsNewRoute: AuthedPollsNewRoute,
  AuthedProfileUserIdRoute: AuthedProfileUserIdRoute,
  AuthedDailyPollIndexRoute: AuthedDailyPollIndexRoute,
  AuthedPollsIndexRoute: AuthedPollsIndexRoute,
  AuthedPollsPollIdEditRoute: AuthedPollsPollIdEditRoute,
  AuthedPollsPollIdIndexRoute: AuthedPollsPollIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AwardsRoute: AwardsRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PresentationRoute: PresentationRoute,
  SignUpRoute: SignUpRoute,
  StartRoute: StartRoute,
  StatsRoute: StatsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
